 constant = {};
 constant.STATUS_STARTED = 'STATUS_STARTED';
 constant.STATUS_NOT_STARTED = 'STATUS_NOT_STARTED';
 constant.STATUS_FAILURE = 'STATUS_FAILURE';
 constant.STATUS_SUCCESS = 'STATUS_SUCCESS';

 constant.PRIORITY_HIGH = 'PRIORITY_HIGH';
 constant.PRIORITY_MEDIUM = 'PRIORITY_MEDIUM';
 constant.PRIORITY_LOW = 'PRIORITY_LOW';